name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows-exe:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pillow
        
    - name: Create application icon
      run: |
        python -c "
        from PIL import Image, ImageDraw
        size = (256, 256)
        img = Image.new('RGBA', size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(img)
        margin = 20
        draw.rectangle([margin, margin, size[0]-margin, size[1]-margin], 
                      fill=(70, 130, 180, 255), outline=(25, 25, 112, 255), width=4)
        draw.text((100, 115), 'OVL', fill=(255, 255, 255, 255))
        img.save('icon.ico', format='ICO', sizes=[(256, 256), (128, 128), (64, 64), (32, 32), (16, 16)])
        "
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name OverlayPy --icon icon.ico overlay.py
        
    - name: Build one-directory version
      run: |
        pyinstaller --onedir --windowed --name OverlayPy-Portable --icon icon.ico overlay.py
        
    - name: Test executable
      run: |
        dist/OverlayPy.exe --help || echo "Executable created (help not implemented)"
        
    - name: Create release package
      run: |
        # Create release directory
        mkdir release
        
        # Copy single executable
        copy dist\OverlayPy.exe release\
        
        # Copy portable version
        xcopy dist\OverlayPy-Portable release\OverlayPy-Portable\ /E /I
        
        # Copy documentation
        copy README.md release\
        copy WINDOWS.md release\
        copy install.bat release\
        copy run-overlay.bat release\
        
        # Create zip file
        powershell Compress-Archive -Path release\* -DestinationPath OverlayPy-Windows.zip
        
    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: OverlayPy-Windows-Executable
        path: |
          dist/OverlayPy.exe
          dist/OverlayPy-Portable/
        retention-days: 30
        
    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: OverlayPy-Windows-Release
        path: OverlayPy-Windows.zip
        retention-days: 90
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OverlayPy-Windows.zip
          dist/OverlayPy.exe
        name: OverlayPy ${{ github.ref_name }}
        body: |
          ## OverlayPy Windows Release ${{ github.ref_name }}
          
          ### Download Options:
          - **OverlayPy.exe** - Single executable file (just download and run)
          - **OverlayPy-Windows.zip** - Complete package with documentation and scripts
          
          ### System Requirements:
          - Windows 7 SP1 or later (Windows 10/11 recommended)
          - No additional software required
          
          ### Quick Start:
          1. Download `OverlayPy.exe`
          2. Double-click to run
          3. Enter your message and click "Show Overlay"
          
          ### Features:
          - Text overlays with customizable font sizes
          - Multi-monitor support
          - Corner positioning
          - Auto-hide timer
          - Click-through overlays (Windows-specific)
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
